version: '3.8'
services:
  # Development mode
    nextapp:
      container_name: frontend
      build:
        context: . 
        target: dev
      command: npm run dev
      environment:
        - NODE_ENV=development
        - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb
      volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
      ports:
        - "3000:3000"
      restart: always
      depends_on:
        - postgres

  # Uncomment the following block for production mode
  # nextapp:
  #   container_name: frontend
  #   image: nextapp
  #   build:
  #     context: .
  #     target: runner
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
